spring:
  application:
    name: nano-worker
  rabbitmq:
    addresses: ${CLOUDAMQP_URL:}
  mail:
    username:
    password:
    host: smtp.office365.com
    port: 587
    properties:
      mail.smtp.starttls.enable: true
